
version: "3.4"

services:

  defiboard_collector:
    hostname: defiboard_collector
    container_name: defiboard_collector
    build:
      context: ./collector
      dockerfile: ./Dockerfile
      labels:
        pro.asix.description: "Defichain Dashboard"
        pro.asix.maintainer: "Raphael Lechner <raphael.lechner@gmail.com>"
        pro.asix.website: "https://defi.raphaellechner.it"
    image: defiboard_collector
    restart: 'always'
    stdin_open: true
    tty: true
    # command: ash

  defiboard_api:
    hostname: defiboard_api
    container_name: defiboard_api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      labels:
        pro.asix.description: "Defichain Dashboard"
        pro.asix.maintainer: "Raphael Lechner <raphael.lechner@gmail.com>"
        pro.asix.website: "https://defi.raphaellechner.it"
    image: defiboard_api
    restart: 'always'
    # volumes:
    #   - ./api:/app
    #   - defiboard_api_node_npm:/app/node_modules
    ports:
      - "3000"
    stdin_open: true
    tty: true
    # command: npm run dev
    labels:
      - traefik.http.routers.defiboard_api.rule=Host(`defichain-board.com`) && Path(`/graphql/`)
      - traefik.http.routers.defiboard_api.tls=true
      - traefik.http.routers.defiboard_api.tls.certresolver=le
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=3000
    networks:
      - traefik
      - default


  mongo:
    image: mongo:4
    hostname: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: defi
      MONGO_INITDB_ROOT_PASSWORD: defi.dev
      MONGO_INITDB_DATABASE: defiboard
    volumes:
      - defiboard_mongo_data:/data/db

volumes:
    defiboard_collector_node_npm:
      external: true
    defiboard_mongo_data:
      external: true
    defiboard_api_node_npm:
      external: true

networks:
  traefik:
    external: true